### ISSUE TITLE
Error require() of ES Module when importing functions

### ISSUE THREAD

**Issue by DarkHollow** [DestinyItemManager/bungie-api-ts#43]
Hello, I'm trying to get the manifest with the example in the readme but when I do the imports, I get error for require() of ES Module.

To reproduce it:

```ts
import { getDestinyManifest, getDestinyManifestSlice } from 'bungie-api-ts/destiny2';
console.log(getDestinyManifest);
```

> the console.log it's for reproduce the problem

Error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /destiny2-api/node_modules/bungie-api-ts/destiny2/index.js from /destiny2-api/src/manifest/index.ts not supported.
Instead change the require of index.js in /destiny2-api/src/manifest/index.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.nodeDevHook [as .js] (/destiny2-api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/destiny2-api/src/manifest/index.ts:42:18)
    at Module._compile (/destiny2-api/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/1m/j_r9mhw56_g26n_8dxw1dkdc0000gn/T/ts-node-dev-hook-8312512297435408.js:69:33)
    at require.extensions.<computed> (/private/var/folders/1m/j_r9mhw56_g26n_8dxw1dkdc0000gn/T/ts-node-dev-hook-8312512297435408.js:71:20)
    at Object.nodeDevHook [as .ts] (/destiny2-api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/destiny2-api/src/prueba/prueba.router.ts:47:34)
    at Module._compile (/destiny2-api/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/1m/j_r9mhw56_g26n_8dxw1dkdc0000gn/T/ts-node-dev-hook-8312512297435408.js:69:33)
    at require.extensions.<computed> (/private/var/folders/1m/j_r9mhw56_g26n_8dxw1dkdc0000gn/T/ts-node-dev-hook-8312512297435408.js:71:20)
    at Object.nodeDevHook [as .ts] (/destiny2-api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/destiny2-api/src/index.ts:29:23)
    at Module._compile (/destiny2-api/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/1m/j_r9mhw56_g26n_8dxw1dkdc0000gn/T/ts-node-dev-hook-8312512297435408.js:69:33)
    at require.extensions.<computed> (/private/var/folders/1m/j_r9mhw56_g26n_8dxw1dkdc0000gn/T/ts-node-dev-hook-8312512297435408.js:71:20)
    at Object.nodeDevHook [as .ts] (/destiny2-api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/destiny2-api/node_modules/ts-node-dev/lib/wrap.js:104:1)
    at Module._compile (/destiny2-api/node_modules/source-map-support/source-map-support.js:568:25)
[ERROR] 19:27:02 Error: require() of ES Module /destiny2-api/node_modules/bungie-api-ts/destiny2/index.js from /destiny2-api/src/manifest/index.ts not supported.
```

If I import types and use them there is no problem, the problem is when I import any function like `getDestinyManifest`.

**Comment by bhollis** [comment]
When using NodeJS, make sure you're on a recent version (16).

**Comment by DarkHollow** [comment]
I'm on NodeJS v16.13.0

```shell
Projects/destiny2/destiny2-api is 📦 v1.0.0 via ⬢ v16.13.0 took 7s 
> node -v
v16.13.0
```

**Comment by DarkHollow** [comment]
Am I doing something wrong?

**Comment by bhollis** [comment]
Not sure. It should work but module support in NodeJS is weird. We've gotten it working for DIM's test code and d2-additional-info (I think) so you can maybe look at them for examples.

**Comment by bhollis** [comment]
Have you tried renaming index.js to index.mjs?

**Comment by delphiactual** [comment]
in d2ai we set the following env variables for node
```
NODE_OPTIONS='--experimental-json-modules'
NODE_NO_WARNINGS=1
```

**Comment by bhollis** [comment]
Worth reading this: https://nodejs.org/api/esm.html

**Comment by DarkHollow** [comment]
Thank you for your help, I managed to setup the tsconfig accorderly to esm and the script with the node option @delphiactual said.

Thank you again!
